// ------------------------------------------------------------------------------
// <copyright company="Kappa Pay Inc.">
// Copyright (C) Kappa Pay Inc.  All rights reserved.
// Unauthorised copying of this file, via any medium, is strictly prohibited.
// Proprietary and confidential
// </copyright>
// <author>Pankaj Pant</author>
// ------------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: kappa/services/linked_accounts/linked_accounts.proto

package linked_accounts

import (
	models "github.com/kappapay/backend/lib/golang/src/kappa/common/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetLinkedAccountsByEntityIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
}

func (x *GetLinkedAccountsByEntityIdRequest) Reset() {
	*x = GetLinkedAccountsByEntityIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountsByEntityIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountsByEntityIdRequest) ProtoMessage() {}

func (x *GetLinkedAccountsByEntityIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountsByEntityIdRequest.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountsByEntityIdRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *GetLinkedAccountsByEntityIdRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetLinkedAccountsByEntityIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccounts []*models.LinkedAccount `protobuf:"bytes,1,rep,name=linked_accounts,json=linkedAccounts,proto3" json:"linked_accounts,omitempty"`
}

func (x *GetLinkedAccountsByEntityIdResponse) Reset() {
	*x = GetLinkedAccountsByEntityIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountsByEntityIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountsByEntityIdResponse) ProtoMessage() {}

func (x *GetLinkedAccountsByEntityIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountsByEntityIdResponse.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountsByEntityIdResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *GetLinkedAccountsByEntityIdResponse) GetLinkedAccounts() []*models.LinkedAccount {
	if x != nil {
		return x.LinkedAccounts
	}
	return nil
}

type GetLinkedAccountByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLinkedAccountByIdRequest) Reset() {
	*x = GetLinkedAccountByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountByIdRequest) ProtoMessage() {}

func (x *GetLinkedAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *GetLinkedAccountByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLinkedAccountByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccount *models.LinkedAccount `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
}

func (x *GetLinkedAccountByIdResponse) Reset() {
	*x = GetLinkedAccountByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkedAccountByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkedAccountByIdResponse) ProtoMessage() {}

func (x *GetLinkedAccountByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkedAccountByIdResponse.ProtoReflect.Descriptor instead.
func (*GetLinkedAccountByIdResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *GetLinkedAccountByIdResponse) GetLinkedAccount() *models.LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type CreateLinkedAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccount *models.LinkedAccount `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
}

func (x *CreateLinkedAccountRequest) Reset() {
	*x = CreateLinkedAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLinkedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkedAccountRequest) ProtoMessage() {}

func (x *CreateLinkedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkedAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkedAccountRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLinkedAccountRequest) GetLinkedAccount() *models.LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type CreateLinkedAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccount *models.LinkedAccount `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
}

func (x *CreateLinkedAccountResponse) Reset() {
	*x = CreateLinkedAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLinkedAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkedAccountResponse) ProtoMessage() {}

func (x *CreateLinkedAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkedAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkedAccountResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLinkedAccountResponse) GetLinkedAccount() *models.LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type UpdateLinkedAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccount *models.LinkedAccount `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
}

func (x *UpdateLinkedAccountRequest) Reset() {
	*x = UpdateLinkedAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLinkedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkedAccountRequest) ProtoMessage() {}

func (x *UpdateLinkedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkedAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkedAccountRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLinkedAccountRequest) GetLinkedAccount() *models.LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type UpdateLinkedAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkedAccount *models.LinkedAccount `protobuf:"bytes,1,opt,name=linked_account,json=linkedAccount,proto3" json:"linked_account,omitempty"`
}

func (x *UpdateLinkedAccountResponse) Reset() {
	*x = UpdateLinkedAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLinkedAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkedAccountResponse) ProtoMessage() {}

func (x *UpdateLinkedAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkedAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkedAccountResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLinkedAccountResponse) GetLinkedAccount() *models.LinkedAccount {
	if x != nil {
		return x.LinkedAccount
	}
	return nil
}

type DeleteLinkedAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLinkedAccountRequest) Reset() {
	*x = DeleteLinkedAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLinkedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkedAccountRequest) ProtoMessage() {}

func (x *DeleteLinkedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkedAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkedAccountRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLinkedAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLinkedAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLinkedAccountResponse) Reset() {
	*x = DeleteLinkedAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLinkedAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkedAccountResponse) ProtoMessage() {}

func (x *DeleteLinkedAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkedAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkedAccountResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLinkedAccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreatePlaidLinkTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId    string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	LanguageId  string `protobuf:"bytes,2,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	RedirectUri string `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
}

func (x *CreatePlaidLinkTokenRequest) Reset() {
	*x = CreatePlaidLinkTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidLinkTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidLinkTokenRequest) ProtoMessage() {}

func (x *CreatePlaidLinkTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidLinkTokenRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaidLinkTokenRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{10}
}

func (x *CreatePlaidLinkTokenRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreatePlaidLinkTokenRequest) GetLanguageId() string {
	if x != nil {
		return x.LanguageId
	}
	return ""
}

func (x *CreatePlaidLinkTokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type CreatePlaidLinkTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkToken  string                 `protobuf:"bytes,1,opt,name=link_token,json=linkToken,proto3" json:"link_token,omitempty"`
	Expiration *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *CreatePlaidLinkTokenResponse) Reset() {
	*x = CreatePlaidLinkTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidLinkTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidLinkTokenResponse) ProtoMessage() {}

func (x *CreatePlaidLinkTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidLinkTokenResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaidLinkTokenResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePlaidLinkTokenResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

func (x *CreatePlaidLinkTokenResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

type ProcessPlaidPublicTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityId string `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// This data should be passed directly from the "onSuccess" callback on the front end.
	// It's currently only needed for audit purposes.
	MetaData *structpb.Struct `protobuf:"bytes,3,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
}

func (x *ProcessPlaidPublicTokenRequest) Reset() {
	*x = ProcessPlaidPublicTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPlaidPublicTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPlaidPublicTokenRequest) ProtoMessage() {}

func (x *ProcessPlaidPublicTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPlaidPublicTokenRequest.ProtoReflect.Descriptor instead.
func (*ProcessPlaidPublicTokenRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessPlaidPublicTokenRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ProcessPlaidPublicTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ProcessPlaidPublicTokenRequest) GetMetaData() *structpb.Struct {
	if x != nil {
		return x.MetaData
	}
	return nil
}

type ProcessPlaidPublicTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessPlaidPublicTokenResponse) Reset() {
	*x = ProcessPlaidPublicTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPlaidPublicTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPlaidPublicTokenResponse) ProtoMessage() {}

func (x *ProcessPlaidPublicTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPlaidPublicTokenResponse.ProtoReflect.Descriptor instead.
func (*ProcessPlaidPublicTokenResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP(), []int{13}
}

var File_kappa_services_linked_accounts_linked_accounts_proto protoreflect.FileDescriptor

var file_kappa_services_linked_accounts_linked_accounts_proto_rawDesc = []byte{
	0x0a, 0x34, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x1a, 0x28, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x41, 0x0a, 0x22, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x23, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x22, 0x2d, 0x0a, 0x1b, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x61,
	0x70, 0x70, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x5a, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0d, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x1a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x6c, 0x69,
	0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5a, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65,
	0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x7e, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c,
	0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x69,
	0x22, 0x79, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c,
	0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x1e,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x34, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x22, 0x21, 0x0a, 0x1f, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xee, 0x06, 0x0a, 0x15, 0x4c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x8a, 0x01, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x33, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x42, 0x79, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x75, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x2e, 0x6c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x72, 0x0a, 0x13,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b,
	0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2c, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x72, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2c, 0x2e, 0x6c,
	0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6c, 0x69, 0x6e,
	0x6b, 0x65, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x7e, 0x0a, 0x17, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2f, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x50, 0x6c, 0x61, 0x69, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4b, 0x5a, 0x49, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x70,
	0x61, 0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x5f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kappa_services_linked_accounts_linked_accounts_proto_rawDescOnce sync.Once
	file_kappa_services_linked_accounts_linked_accounts_proto_rawDescData = file_kappa_services_linked_accounts_linked_accounts_proto_rawDesc
)

func file_kappa_services_linked_accounts_linked_accounts_proto_rawDescGZIP() []byte {
	file_kappa_services_linked_accounts_linked_accounts_proto_rawDescOnce.Do(func() {
		file_kappa_services_linked_accounts_linked_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(file_kappa_services_linked_accounts_linked_accounts_proto_rawDescData)
	})
	return file_kappa_services_linked_accounts_linked_accounts_proto_rawDescData
}

var file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_kappa_services_linked_accounts_linked_accounts_proto_goTypes = []interface{}{
	(*GetLinkedAccountsByEntityIdRequest)(nil),  // 0: linked_accounts.GetLinkedAccountsByEntityIdRequest
	(*GetLinkedAccountsByEntityIdResponse)(nil), // 1: linked_accounts.GetLinkedAccountsByEntityIdResponse
	(*GetLinkedAccountByIdRequest)(nil),         // 2: linked_accounts.GetLinkedAccountByIdRequest
	(*GetLinkedAccountByIdResponse)(nil),        // 3: linked_accounts.GetLinkedAccountByIdResponse
	(*CreateLinkedAccountRequest)(nil),          // 4: linked_accounts.CreateLinkedAccountRequest
	(*CreateLinkedAccountResponse)(nil),         // 5: linked_accounts.CreateLinkedAccountResponse
	(*UpdateLinkedAccountRequest)(nil),          // 6: linked_accounts.UpdateLinkedAccountRequest
	(*UpdateLinkedAccountResponse)(nil),         // 7: linked_accounts.UpdateLinkedAccountResponse
	(*DeleteLinkedAccountRequest)(nil),          // 8: linked_accounts.DeleteLinkedAccountRequest
	(*DeleteLinkedAccountResponse)(nil),         // 9: linked_accounts.DeleteLinkedAccountResponse
	(*CreatePlaidLinkTokenRequest)(nil),         // 10: linked_accounts.CreatePlaidLinkTokenRequest
	(*CreatePlaidLinkTokenResponse)(nil),        // 11: linked_accounts.CreatePlaidLinkTokenResponse
	(*ProcessPlaidPublicTokenRequest)(nil),      // 12: linked_accounts.ProcessPlaidPublicTokenRequest
	(*ProcessPlaidPublicTokenResponse)(nil),     // 13: linked_accounts.ProcessPlaidPublicTokenResponse
	(*models.LinkedAccount)(nil),                // 14: kappa.LinkedAccount
	(*timestamppb.Timestamp)(nil),               // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                     // 16: google.protobuf.Struct
}
var file_kappa_services_linked_accounts_linked_accounts_proto_depIdxs = []int32{
	14, // 0: linked_accounts.GetLinkedAccountsByEntityIdResponse.linked_accounts:type_name -> kappa.LinkedAccount
	14, // 1: linked_accounts.GetLinkedAccountByIdResponse.linked_account:type_name -> kappa.LinkedAccount
	14, // 2: linked_accounts.CreateLinkedAccountRequest.linked_account:type_name -> kappa.LinkedAccount
	14, // 3: linked_accounts.CreateLinkedAccountResponse.linked_account:type_name -> kappa.LinkedAccount
	14, // 4: linked_accounts.UpdateLinkedAccountRequest.linked_account:type_name -> kappa.LinkedAccount
	14, // 5: linked_accounts.UpdateLinkedAccountResponse.linked_account:type_name -> kappa.LinkedAccount
	15, // 6: linked_accounts.CreatePlaidLinkTokenResponse.expiration:type_name -> google.protobuf.Timestamp
	16, // 7: linked_accounts.ProcessPlaidPublicTokenRequest.meta_data:type_name -> google.protobuf.Struct
	0,  // 8: linked_accounts.LinkedAccountsService.GetLinkedAccountsByEntityId:input_type -> linked_accounts.GetLinkedAccountsByEntityIdRequest
	2,  // 9: linked_accounts.LinkedAccountsService.GetLinkedAccountById:input_type -> linked_accounts.GetLinkedAccountByIdRequest
	4,  // 10: linked_accounts.LinkedAccountsService.CreateLinkedAccount:input_type -> linked_accounts.CreateLinkedAccountRequest
	6,  // 11: linked_accounts.LinkedAccountsService.UpdateLinkedAccount:input_type -> linked_accounts.UpdateLinkedAccountRequest
	8,  // 12: linked_accounts.LinkedAccountsService.DeleteLinkedAccount:input_type -> linked_accounts.DeleteLinkedAccountRequest
	10, // 13: linked_accounts.LinkedAccountsService.CreatePlaidLinkToken:input_type -> linked_accounts.CreatePlaidLinkTokenRequest
	12, // 14: linked_accounts.LinkedAccountsService.ProcessPlaidPublicToken:input_type -> linked_accounts.ProcessPlaidPublicTokenRequest
	1,  // 15: linked_accounts.LinkedAccountsService.GetLinkedAccountsByEntityId:output_type -> linked_accounts.GetLinkedAccountsByEntityIdResponse
	3,  // 16: linked_accounts.LinkedAccountsService.GetLinkedAccountById:output_type -> linked_accounts.GetLinkedAccountByIdResponse
	5,  // 17: linked_accounts.LinkedAccountsService.CreateLinkedAccount:output_type -> linked_accounts.CreateLinkedAccountResponse
	7,  // 18: linked_accounts.LinkedAccountsService.UpdateLinkedAccount:output_type -> linked_accounts.UpdateLinkedAccountResponse
	9,  // 19: linked_accounts.LinkedAccountsService.DeleteLinkedAccount:output_type -> linked_accounts.DeleteLinkedAccountResponse
	11, // 20: linked_accounts.LinkedAccountsService.CreatePlaidLinkToken:output_type -> linked_accounts.CreatePlaidLinkTokenResponse
	13, // 21: linked_accounts.LinkedAccountsService.ProcessPlaidPublicToken:output_type -> linked_accounts.ProcessPlaidPublicTokenResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_kappa_services_linked_accounts_linked_accounts_proto_init() }
func file_kappa_services_linked_accounts_linked_accounts_proto_init() {
	if File_kappa_services_linked_accounts_linked_accounts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountsByEntityIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountsByEntityIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkedAccountByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLinkedAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLinkedAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLinkedAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLinkedAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLinkedAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLinkedAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidLinkTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidLinkTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPlaidPublicTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPlaidPublicTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kappa_services_linked_accounts_linked_accounts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kappa_services_linked_accounts_linked_accounts_proto_goTypes,
		DependencyIndexes: file_kappa_services_linked_accounts_linked_accounts_proto_depIdxs,
		MessageInfos:      file_kappa_services_linked_accounts_linked_accounts_proto_msgTypes,
	}.Build()
	File_kappa_services_linked_accounts_linked_accounts_proto = out.File
	file_kappa_services_linked_accounts_linked_accounts_proto_rawDesc = nil
	file_kappa_services_linked_accounts_linked_accounts_proto_goTypes = nil
	file_kappa_services_linked_accounts_linked_accounts_proto_depIdxs = nil
}
