// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: kappa/services/emails/emails.proto

package emails

import (
	models "github.com/kappapay/backend/lib/golang/src/kappa/common/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEmailAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateEmailAddressRequest) Reset() {
	*x = CreateEmailAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmailAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailAddressRequest) ProtoMessage() {}

func (x *CreateEmailAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateEmailAddressRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEmailAddressRequest) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type CreateEmailAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CreateEmailAddressResponse) Reset() {
	*x = CreateEmailAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmailAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmailAddressResponse) ProtoMessage() {}

func (x *CreateEmailAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmailAddressResponse.ProtoReflect.Descriptor instead.
func (*CreateEmailAddressResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmailAddressResponse) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type GetEmailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
}

func (x *GetEmailRequest) Reset() {
	*x = GetEmailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailRequest) ProtoMessage() {}

func (x *GetEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailRequest.ProtoReflect.Descriptor instead.
func (*GetEmailRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmailRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

type GetEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetEmailResponse) Reset() {
	*x = GetEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailResponse) ProtoMessage() {}

func (x *GetEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailResponse.ProtoReflect.Descriptor instead.
func (*GetEmailResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{3}
}

func (x *GetEmailResponse) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type GetEmailByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEmailByIDRequest) Reset() {
	*x = GetEmailByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIDRequest) ProtoMessage() {}

func (x *GetEmailByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIDRequest.ProtoReflect.Descriptor instead.
func (*GetEmailByIDRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{4}
}

func (x *GetEmailByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEmailByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetEmailByIDResponse) Reset() {
	*x = GetEmailByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByIDResponse) ProtoMessage() {}

func (x *GetEmailByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByIDResponse.ProtoReflect.Descriptor instead.
func (*GetEmailByIDResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{5}
}

func (x *GetEmailByIDResponse) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type UpdateEmailAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UpdateEmailAddressRequest) Reset() {
	*x = UpdateEmailAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmailAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailAddressRequest) ProtoMessage() {}

func (x *UpdateEmailAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailAddressRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmailAddressRequest) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type UpdateEmailAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *UpdateEmailAddressResponse) Reset() {
	*x = UpdateEmailAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEmailAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailAddressResponse) ProtoMessage() {}

func (x *UpdateEmailAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailAddressResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEmailAddressResponse) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type DeleteEmailAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
}

func (x *DeleteEmailAddressRequest) Reset() {
	*x = DeleteEmailAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmailAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailAddressRequest) ProtoMessage() {}

func (x *DeleteEmailAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailAddressRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEmailAddressRequest) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

type DeleteEmailAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *DeleteEmailAddressResponse) Reset() {
	*x = DeleteEmailAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmailAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailAddressResponse) ProtoMessage() {}

func (x *DeleteEmailAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmailAddressResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEmailAddressResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type DeleteEmailAddressByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEmailAddressByIDRequest) Reset() {
	*x = DeleteEmailAddressByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmailAddressByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailAddressByIDRequest) ProtoMessage() {}

func (x *DeleteEmailAddressByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailAddressByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmailAddressByIDRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEmailAddressByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEmailAddressByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
}

func (x *DeleteEmailAddressByIDResponse) Reset() {
	*x = DeleteEmailAddressByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmailAddressByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmailAddressByIDResponse) ProtoMessage() {}

func (x *DeleteEmailAddressByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmailAddressByIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteEmailAddressByIDResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEmailAddressByIDResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type MarkEmailVerifiedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorHandle string `protobuf:"bytes,1,opt,name=vendor_handle,json=vendorHandle,proto3" json:"vendor_handle,omitempty"`
}

func (x *MarkEmailVerifiedRequest) Reset() {
	*x = MarkEmailVerifiedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkEmailVerifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkEmailVerifiedRequest) ProtoMessage() {}

func (x *MarkEmailVerifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkEmailVerifiedRequest.ProtoReflect.Descriptor instead.
func (*MarkEmailVerifiedRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{12}
}

func (x *MarkEmailVerifiedRequest) GetVendorHandle() string {
	if x != nil {
		return x.VendorHandle
	}
	return ""
}

type MarkEmailVerifiedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MarkEmailVerifiedResponse) Reset() {
	*x = MarkEmailVerifiedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkEmailVerifiedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkEmailVerifiedResponse) ProtoMessage() {}

func (x *MarkEmailVerifiedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkEmailVerifiedResponse.ProtoReflect.Descriptor instead.
func (*MarkEmailVerifiedResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{13}
}

type GetEmailByVendorHandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VendorHandle string `protobuf:"bytes,1,opt,name=vendor_handle,json=vendorHandle,proto3" json:"vendor_handle,omitempty"`
}

func (x *GetEmailByVendorHandleRequest) Reset() {
	*x = GetEmailByVendorHandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailByVendorHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByVendorHandleRequest) ProtoMessage() {}

func (x *GetEmailByVendorHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByVendorHandleRequest.ProtoReflect.Descriptor instead.
func (*GetEmailByVendorHandleRequest) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{14}
}

func (x *GetEmailByVendorHandleRequest) GetVendorHandle() string {
	if x != nil {
		return x.VendorHandle
	}
	return ""
}

type GetEmailByVendorHandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email *models.Email `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetEmailByVendorHandleResponse) Reset() {
	*x = GetEmailByVendorHandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kappa_services_emails_emails_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEmailByVendorHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailByVendorHandleResponse) ProtoMessage() {}

func (x *GetEmailByVendorHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kappa_services_emails_emails_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailByVendorHandleResponse.ProtoReflect.Descriptor instead.
func (*GetEmailByVendorHandleResponse) Descriptor() ([]byte, []int) {
	return file_kappa_services_emails_emails_proto_rawDescGZIP(), []int{15}
}

func (x *GetEmailByVendorHandleResponse) GetEmail() *models.Email {
	if x != nil {
		return x.Email
	}
	return nil
}

var File_kappa_services_emails_emails_proto protoreflect.FileDescriptor

var file_kappa_services_emails_emails_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x1a, 0x1f, 0x6b, 0x61,
	0x70, 0x70, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f,
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x61, 0x70,
	0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x40, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0x36, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b,
	0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3f, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x40, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x40, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x57, 0x0a, 0x1a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x2f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x5b, 0x0a, 0x1e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x3f, 0x0a, 0x18, 0x4d, 0x61, 0x72, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x22, 0x1b, 0x0a, 0x19, 0x4d, 0x61, 0x72, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x44,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x56, 0x65, 0x6e, 0x64,
	0x6f, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x42, 0x79, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2e, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x32, 0xde, 0x05, 0x0a, 0x0c, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x21, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x2e,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x52, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x2e, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x2e, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x12, 0x25,
	0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x2e, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5a, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x12, 0x20, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e, 0x4d, 0x61,
	0x72, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x2e,
	0x4d, 0x61, 0x72, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x42, 0x5a, 0x40, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x70,
	0x61, 0x79, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x6b, 0x61, 0x70, 0x70, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kappa_services_emails_emails_proto_rawDescOnce sync.Once
	file_kappa_services_emails_emails_proto_rawDescData = file_kappa_services_emails_emails_proto_rawDesc
)

func file_kappa_services_emails_emails_proto_rawDescGZIP() []byte {
	file_kappa_services_emails_emails_proto_rawDescOnce.Do(func() {
		file_kappa_services_emails_emails_proto_rawDescData = protoimpl.X.CompressGZIP(file_kappa_services_emails_emails_proto_rawDescData)
	})
	return file_kappa_services_emails_emails_proto_rawDescData
}

var file_kappa_services_emails_emails_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_kappa_services_emails_emails_proto_goTypes = []interface{}{
	(*CreateEmailAddressRequest)(nil),      // 0: emails.CreateEmailAddressRequest
	(*CreateEmailAddressResponse)(nil),     // 1: emails.CreateEmailAddressResponse
	(*GetEmailRequest)(nil),                // 2: emails.GetEmailRequest
	(*GetEmailResponse)(nil),               // 3: emails.GetEmailResponse
	(*GetEmailByIDRequest)(nil),            // 4: emails.GetEmailByIDRequest
	(*GetEmailByIDResponse)(nil),           // 5: emails.GetEmailByIDResponse
	(*UpdateEmailAddressRequest)(nil),      // 6: emails.UpdateEmailAddressRequest
	(*UpdateEmailAddressResponse)(nil),     // 7: emails.UpdateEmailAddressResponse
	(*DeleteEmailAddressRequest)(nil),      // 8: emails.DeleteEmailAddressRequest
	(*DeleteEmailAddressResponse)(nil),     // 9: emails.DeleteEmailAddressResponse
	(*DeleteEmailAddressByIDRequest)(nil),  // 10: emails.DeleteEmailAddressByIDRequest
	(*DeleteEmailAddressByIDResponse)(nil), // 11: emails.DeleteEmailAddressByIDResponse
	(*MarkEmailVerifiedRequest)(nil),       // 12: emails.MarkEmailVerifiedRequest
	(*MarkEmailVerifiedResponse)(nil),      // 13: emails.MarkEmailVerifiedResponse
	(*GetEmailByVendorHandleRequest)(nil),  // 14: emails.GetEmailByVendorHandleRequest
	(*GetEmailByVendorHandleResponse)(nil), // 15: emails.GetEmailByVendorHandleResponse
	(*models.Email)(nil),                   // 16: kappa.Email
	(*timestamppb.Timestamp)(nil),          // 17: google.protobuf.Timestamp
}
var file_kappa_services_emails_emails_proto_depIdxs = []int32{
	16, // 0: emails.CreateEmailAddressRequest.email:type_name -> kappa.Email
	16, // 1: emails.CreateEmailAddressResponse.email:type_name -> kappa.Email
	16, // 2: emails.GetEmailResponse.email:type_name -> kappa.Email
	16, // 3: emails.GetEmailByIDResponse.email:type_name -> kappa.Email
	16, // 4: emails.UpdateEmailAddressRequest.email:type_name -> kappa.Email
	16, // 5: emails.UpdateEmailAddressResponse.email:type_name -> kappa.Email
	17, // 6: emails.DeleteEmailAddressResponse.deleted_at:type_name -> google.protobuf.Timestamp
	17, // 7: emails.DeleteEmailAddressByIDResponse.deleted_at:type_name -> google.protobuf.Timestamp
	16, // 8: emails.GetEmailByVendorHandleResponse.email:type_name -> kappa.Email
	0,  // 9: emails.EmailService.CreateEmailAddress:input_type -> emails.CreateEmailAddressRequest
	2,  // 10: emails.EmailService.GetEmailAddress:input_type -> emails.GetEmailRequest
	4,  // 11: emails.EmailService.GetEmailAddressByID:input_type -> emails.GetEmailByIDRequest
	6,  // 12: emails.EmailService.UpdateEmailAddress:input_type -> emails.UpdateEmailAddressRequest
	8,  // 13: emails.EmailService.DeleteEmailAddress:input_type -> emails.DeleteEmailAddressRequest
	10, // 14: emails.EmailService.DeleteEmailAddressByID:input_type -> emails.DeleteEmailAddressByIDRequest
	2,  // 15: emails.EmailService.GetOrCreateEmailAddress:input_type -> emails.GetEmailRequest
	12, // 16: emails.EmailService.MarkEmailVerified:input_type -> emails.MarkEmailVerifiedRequest
	1,  // 17: emails.EmailService.CreateEmailAddress:output_type -> emails.CreateEmailAddressResponse
	3,  // 18: emails.EmailService.GetEmailAddress:output_type -> emails.GetEmailResponse
	5,  // 19: emails.EmailService.GetEmailAddressByID:output_type -> emails.GetEmailByIDResponse
	7,  // 20: emails.EmailService.UpdateEmailAddress:output_type -> emails.UpdateEmailAddressResponse
	9,  // 21: emails.EmailService.DeleteEmailAddress:output_type -> emails.DeleteEmailAddressResponse
	11, // 22: emails.EmailService.DeleteEmailAddressByID:output_type -> emails.DeleteEmailAddressByIDResponse
	3,  // 23: emails.EmailService.GetOrCreateEmailAddress:output_type -> emails.GetEmailResponse
	13, // 24: emails.EmailService.MarkEmailVerified:output_type -> emails.MarkEmailVerifiedResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_kappa_services_emails_emails_proto_init() }
func file_kappa_services_emails_emails_proto_init() {
	if File_kappa_services_emails_emails_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kappa_services_emails_emails_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmailAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmailAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmailAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEmailAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmailAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmailAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmailAddressByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmailAddressByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkEmailVerifiedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkEmailVerifiedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailByVendorHandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kappa_services_emails_emails_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEmailByVendorHandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kappa_services_emails_emails_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kappa_services_emails_emails_proto_goTypes,
		DependencyIndexes: file_kappa_services_emails_emails_proto_depIdxs,
		MessageInfos:      file_kappa_services_emails_emails_proto_msgTypes,
	}.Build()
	File_kappa_services_emails_emails_proto = out.File
	file_kappa_services_emails_emails_proto_rawDesc = nil
	file_kappa_services_emails_emails_proto_goTypes = nil
	file_kappa_services_emails_emails_proto_depIdxs = nil
}
